baseurl = "http://www.michaelroberts.website/"
title = "Michael Roberts Website"
theme = "main"
languageCode = "en-us"

[menu]
  [[menu.header]]
    name = "Resume"
    weight = 1
    url = "/resume.pdf"
  [[menu.header]]	
    name = "about"
    weight = 1
    url = "/about"
  [[menu.header]]
	name = "Projects"	
	weight = 2
	url = "/projects"

[params]
  GithubID = "michaelroberts98"
  TwitterID = "theWindowsTwin"
  LinkedInID = "michael-roberts-ucf"
  Name = "Michael Roberts"
  HeaderUsername = "Michaelroberts"
  HeaderHostname = "email.com"
  Email = "michaelroberts@hackucf.org"
  About = "Hi I'm Michael and this is my website. I am a student, speaker and competitor. On this website you can expect to see my projects and some of my experiences. Enjoy!"
  ProfilePicture = "/profile.jpeg"
  Favicon = "/favicon.ico"

